export type EventCategory = 'film' | 'music' | 'lecture' | 'exhibition' | 'performance'

export interface OutsideEvent {
  id: string
  slug: string
  index: number
  title: string
  subtitle?: string
  venue: string
  venueSlug: string
  city: string
  date: string
  time: string
  doorsTime?: string
  category: EventCategory
  description: string
  price: string
  tags: string[]
  isPast?: boolean
}

const EVENTS: OutsideEvent[] = [
  {
    id: '001',
    slug: 'je-tu-il-elle',
    index: 1,
    title: 'Je Tu Il Elle',
    subtitle: 'Dir. Chantal Akerman, 1974 — 16mm',
    venue: 'Metrograph',
    venueSlug: 'metrograph',
    city: 'New York',
    date: '2026-06-04',
    time: '20:00',
    category: 'film',
    price: '$15',
    description: 'A young woman — played by Akerman herself — passes through three encounters: isolation with sugar and a mattress, a truck driver\'s muted companionship, an erotic reunion with a former lover. Shot in 16mm over four days. Presented as part of the Metrograph\'s extended Akerman retrospective.',
    tags: ['Akerman', 'Belgian Cinema', 'Feminist Cinema']
  },
  {
    id: '002',
    slug: 'objekt',
    index: 2,
    title: 'Objekt',
    subtitle: 'Live — North American Tour',
    venue: 'Output',
    venueSlug: 'output',
    city: 'Brooklyn',
    date: '2026-06-06',
    time: '23:00',
    doorsTime: '22:00',
    category: 'music',
    price: '$22',
    description: 'Berlin-based producer T.J. Hertz plays a rare live set at Output. Expect hard-edged, genre-collapsing electronic music that moves between UK hardcore, industrial, and the edge of floor-functional. One of the most disciplined selectors in contemporary club music.',
    tags: ['Techno', 'Experimental', 'Berlin']
  },
  {
    id: '003',
    slug: 'hito-steyerl-visibility',
    index: 3,
    title: 'How Not To Be Seen',
    subtitle: 'A lecture by Hito Steyerl',
    venue: 'Pioneer Works',
    venueSlug: 'pioneer-works',
    city: 'Brooklyn',
    date: '2026-06-11',
    time: '19:00',
    category: 'lecture',
    price: 'Free',
    description: 'Artist and filmmaker Hito Steyerl speaks on machine vision, the aesthetics of resolution, and what it means to disappear in an era of algorithmic surveillance. An extension of her ongoing inquiry into the politics of image-making. Co-presented with The New School.',
    tags: ['Media Theory', 'AI', 'Contemporary Art']
  },
  {
    id: '004',
    slug: 'simone-leigh-sovereignty',
    index: 4,
    title: 'Simone Leigh: Sovereignty',
    subtitle: 'Survey exhibition',
    venue: 'The Kitchen',
    venueSlug: 'the-kitchen',
    city: 'New York',
    date: '2026-06-13',
    time: '11:00',
    category: 'exhibition',
    price: '$20',
    description: 'The first comprehensive New York survey of Simone Leigh\'s practice — sculpture, video, and performance spanning two decades. Centering Black feminine subjectivity, archival knowledge production, and the politics of care. Open through early June.',
    tags: ['Sculpture', 'Black Feminism', 'Contemporary']
  },
  {
    id: '005',
    slug: 'stalker',
    index: 5,
    title: 'Stalker',
    subtitle: 'Dir. Andrei Tarkovsky, 1979 — 4K restoration',
    venue: 'Anthology Film Archives',
    venueSlug: 'anthology',
    city: 'New York',
    date: '2026-06-18',
    time: '19:30',
    category: 'film',
    price: '$16',
    description: 'A guide leads two men through a forbidden area known as the Zone, toward a room said to grant one\'s innermost desires. New 4K restoration from Mosfilm archives. 163 minutes. The Zone has never looked so present. Post-screening discussion with the programmer.',
    tags: ['Tarkovsky', 'Soviet Cinema', 'Restoration']
  },
  {
    id: '006',
    slug: 'rite-of-spring',
    index: 6,
    title: 'The Rite of Spring',
    subtitle: 'Tanztheater Wuppertal Pina Bausch',
    venue: 'BAM Howard Gilman Opera House',
    venueSlug: 'bam',
    city: 'Brooklyn',
    date: '2026-06-20',
    time: '19:30',
    category: 'performance',
    price: '$55',
    description: 'Pina Bausch\'s monumental Rite of Spring, performed on a stage covered in earth. The bodies that fall and rise from the soil are all that stand between Stravinsky\'s score and something more ancient. A defining work of the twentieth century, performed by the company Bausch built.',
    tags: ['Dance', 'Stravinsky', 'Bausch']
  },
  {
    id: '007',
    slug: 'platform-as-publisher',
    index: 7,
    title: 'Platform as Publisher',
    subtitle: 'Symposium on digital infrastructure and cultural power',
    venue: 'The New School',
    venueSlug: 'new-school',
    city: 'New York',
    date: '2026-06-25',
    time: '10:00',
    category: 'lecture',
    price: 'Free',
    description: 'A half-day symposium on the political economy of digital platforms as cultural gatekeepers. Speakers from media criticism, engineering, and independent publishing. What happens to culture when distribution is owned by four companies?',
    tags: ['Digital Culture', 'Media Theory', 'Politics']
  },
  {
    id: '008',
    slug: 'arca-live',
    index: 8,
    title: 'Arca',
    subtitle: 'Kick Tour — Live A/V',
    venue: 'Knockdown Center',
    venueSlug: 'knockdown-center',
    city: 'Queens',
    date: '2026-06-27',
    time: '21:00',
    doorsTime: '20:00',
    category: 'music',
    price: '$35',
    description: 'Venezuelan producer and performance artist Alejandra Ghersi presents her most visceral live show to date — surround sound, full visual system, and a set that refuses all genre containment. Presented in Knockdown Center\'s main hall. Support from SHYBOI.',
    tags: ['Electronic', 'Experimental', 'Performance Art']
  },
  {
    id: '009',
    slug: 'jeanne-dielman',
    index: 9,
    title: 'Jeanne Dielman, 23 Commerce Quay',
    subtitle: 'Dir. Chantal Akerman, 1975 — DCP restoration',
    venue: 'Metrograph',
    venueSlug: 'metrograph',
    city: 'New York',
    date: '2026-07-02',
    time: '18:30',
    category: 'film',
    price: '$16',
    description: 'Akerman\'s three-and-a-half hour portrait of a Brussels housewife — structured around three days of domestic routine and its slow, irreversible unraveling. A newly struck DCP from the Akerman estate. Often cited as the greatest film ever made; consistently underscreened. Post-screening discussion with the programmer.',
    tags: ['Akerman', 'Belgian Cinema', 'Feminist Cinema', 'Restoration']
  },
  {
    id: '010',
    slug: 'grouper-national-sawdust',
    index: 10,
    title: 'Grouper',
    subtitle: 'Solo — Dragging a Dead Deer Up a Hill',
    venue: 'National Sawdust',
    venueSlug: 'national-sawdust',
    city: 'Brooklyn',
    date: '2026-07-08',
    time: '20:30',
    doorsTime: '19:30',
    category: 'music',
    price: '$28',
    description: 'Liz Harris performs solo — voice, guitar, and tape loops — in National Sawdust\'s intimate main space. Grouper\'s live shows are vanishingly rare and function more like séances than concerts. The room holds 200. Expect silence, reverb, and the particular quality of attention that only she produces.',
    tags: ['Ambient', 'Drone', 'Solo Performance']
  },
  {
    id: '011',
    slug: 'kara-walker-drawing-center',
    index: 11,
    title: 'Kara Walker: Hysterical',
    subtitle: 'New works on paper',
    venue: 'The Drawing Center',
    venueSlug: 'drawing-center',
    city: 'New York',
    date: '2026-07-11',
    time: '11:00',
    category: 'exhibition',
    price: '$5',
    description: 'A new body of works on paper by Kara Walker — silhouette, gouache, and text engaging the psychoanalytic tradition and its colonial inheritance. Walker\'s first solo presentation at The Drawing Center since 1994. The works circle questions of who gets to claim madness and at what cost.',
    tags: ['Drawing', 'Contemporary Art', 'Black Art', 'History']
  },
  {
    id: '012',
    slug: 'jlin-knockdown-center',
    index: 12,
    title: 'Jlin',
    subtitle: 'Perspective Tour — Live',
    venue: 'Knockdown Center',
    venueSlug: 'knockdown-center',
    city: 'Queens',
    date: '2026-07-16',
    time: '22:00',
    doorsTime: '21:00',
    category: 'music',
    price: '$30',
    description: 'Gary, Indiana\'s Jerrilynn Patton brings her live set to Knockdown Center — footwork rhythms folded through contemporary classical influence, denser and more disorienting than her records suggest. One of the most technically formidable producers working. The floor will move.',
    tags: ['Footwork', 'Electronic', 'Experimental']
  },
  {
    id: '013',
    slug: 'ali-fear-eats-the-soul',
    index: 13,
    title: 'Ali: Fear Eats the Soul',
    subtitle: 'Dir. Rainer Werner Fassbinder, 1974 — 35mm',
    venue: 'Anthology Film Archives',
    venueSlug: 'anthology',
    city: 'New York',
    date: '2026-07-19',
    time: '19:00',
    category: 'film',
    price: '$15',
    description: 'An elderly German cleaning woman falls in love with a young Moroccan mechanic — Fassbinder\'s most economical and devastating dissection of racism, class, and the violence of social convention. Shot in eight days. A restored 35mm print from the Fassbinder Foundation. 93 minutes.',
    tags: ['Fassbinder', 'German Cinema', '35mm', 'New German Cinema']
  },
  {
    id: '014',
    slug: 'lucy-sante-low-life',
    index: 14,
    title: 'Lucy Sante: Low Life',
    subtitle: 'Lecture — on the vanished New York',
    venue: 'Pioneer Works',
    venueSlug: 'pioneer-works',
    city: 'Brooklyn',
    date: '2026-07-23',
    time: '19:00',
    category: 'lecture',
    price: '$10',
    description: 'Author and critic Lucy Sante speaks on the research, writing, and afterlife of Low Life — her 1991 account of the underworld that built lower Manhattan. The talk addresses what it means to document a city that keeps erasing itself, and what the archive can and cannot hold. Moderated by Rachel Kushner.',
    tags: ['NYC History', 'Literature', 'Archive', 'Downtown']
  },
  {
    id: '015',
    slug: 'trisha-brown-accumulation',
    index: 15,
    title: 'Trisha Brown Dance Company',
    subtitle: 'Accumulation with Talking — Restaging',
    venue: 'BAM Harvey Theater',
    venueSlug: 'bam-harvey',
    city: 'Brooklyn',
    date: '2026-07-26',
    time: '19:30',
    category: 'performance',
    price: '$40',
    description: 'The Trisha Brown Dance Company performs a rare restaging of Accumulation (1971) and Accumulation with Talking Plus Watermotor (1978) — two of the foundational works of postmodern dance, performed in the stripped BAM Harvey. A chance to see work that changed what the body on stage could mean.',
    tags: ['Postmodern Dance', 'Downtown NY', 'Restaging', 'Trisha Brown']
  },
  {
    id: '016',
    slug: 'eartheater-brooklyn-steel',
    index: 16,
    title: 'Eartheater',
    subtitle: 'Phoenix: Flames Are Dew Upon My Skin — Live A/V',
    venue: 'Brooklyn Steel',
    venueSlug: 'brooklyn-steel',
    city: 'Brooklyn',
    date: '2026-07-31',
    time: '21:00',
    doorsTime: '20:00',
    category: 'music',
    price: '$28',
    description: 'Alexandra Drewchin presents the full live A/V production of Phoenix alongside new material. Eartheater\'s live show is difficult to categorize and easy to remember: operatic in scale, intimate in address. Harp, processed vocals, and fractured pop that refuses to resolve. Support from LSDXOXO.',
    tags: ['Experimental Pop', 'Electronic', 'A/V Performance']
  },
  {
    id: '017',
    slug: 'cleo-from-5-to-7',
    index: 17,
    title: 'Cléo from 5 to 7',
    subtitle: 'Dir. Agnès Varda, 1962 — 4K restoration',
    venue: 'Film Forum',
    venueSlug: 'film-forum',
    city: 'New York',
    date: '2026-08-06',
    time: '19:30',
    category: 'film',
    price: '$15',
    description: 'A singer waits two hours for medical results that may confirm cancer — Varda\'s masterpiece of real-time filmmaking, shot on location in Paris in the early sixties. A new 4K restoration from Ciné-Tamaris. The film runs 90 minutes; it lasts much longer. Introduction by the programmer.',
    tags: ['Varda', 'French New Wave', 'Feminist Cinema', '4K Restoration']
  },
  {
    id: '018',
    slug: 'meredith-monk-early-works',
    index: 18,
    title: 'Meredith Monk: Early Works',
    subtitle: 'Juice, Vessel — Restaged',
    venue: 'The Kitchen',
    venueSlug: 'the-kitchen',
    city: 'New York',
    date: '2026-08-09',
    time: '19:00',
    category: 'performance',
    price: '$35',
    description: 'Meredith Monk performs reconstructions of Juice (1969) and Vessel (1971) — two of her landmark early works, adapted for The Kitchen\'s main room. The performances involve extended vocal technique, movement, and the layered spatial consciousness that defined Monk\'s contribution to interdisciplinary performance.',
    tags: ['Vocal Music', 'Performance Art', 'Reconstruction', 'Meredith Monk']
  },
  {
    id: '019',
    slug: 'wolfgang-tillmans-lighter',
    index: 19,
    title: 'Wolfgang Tillmans: Lighter',
    subtitle: 'Survey exhibition',
    venue: 'ICP Museum',
    venueSlug: 'icp',
    city: 'New York',
    date: '2026-08-14',
    time: '11:00',
    category: 'exhibition',
    price: '$16',
    description: 'A comprehensive survey of Wolfgang Tillmans\'s photographic practice from 1990 to the present — rave culture, portraiture, abstraction, and the political image. Over 200 works from international collections, reinstalled according to Tillmans\'s characteristic unframed, pinned presentation.',
    tags: ['Photography', 'Contemporary Art', 'Club Culture', 'Portraiture']
  },
  {
    id: '020',
    slug: 'sun-ra-arkestra',
    index: 20,
    title: 'Sun Ra Arkestra',
    subtitle: 'Under the direction of Marshall Allen',
    venue: 'Brooklyn Steel',
    venueSlug: 'brooklyn-steel',
    city: 'Brooklyn',
    date: '2026-08-21',
    time: '20:00',
    doorsTime: '19:00',
    category: 'music',
    price: '$35',
    description: 'The Sun Ra Arkestra — still performing, still costumed, still otherworldly — under the direction of Marshall Allen. The setlist moves through the Arkestra\'s six-decade catalogue, from Heliocentric Worlds to Lanquidity, and on into the space music beyond. One of the last living connections to this particular American avant-garde.',
    tags: ['Jazz', 'Avant-garde', 'Free Jazz', 'Sun Ra']
  },
  {
    id: '021',
    slug: 'wr-mysteries-organism',
    index: 21,
    title: 'WR: Mysteries of the Organism',
    subtitle: 'Dir. Dušan Makavejev, 1971 — 35mm',
    venue: 'Anthology Film Archives',
    venueSlug: 'anthology',
    city: 'New York',
    date: '2026-08-27',
    time: '19:30',
    category: 'film',
    price: '$15',
    description: 'Makavejev weaves documentary footage of Wilhelm Reich with a fictional Yugoslav love story — a formally reckless, politically charged film that got him banned from his own country upon release. A struck 35mm print from Janus Films. Funny, carnal, and still dangerous. 84 minutes.',
    tags: ['Yugoslav Cinema', '35mm', 'Political Cinema', 'Makavejev']
  },
  {
    id: '022',
    slug: 'adrienne-kennedy-funnyhouse',
    index: 22,
    title: 'Adrienne Kennedy: Funnyhouse of a Negro',
    subtitle: 'Revival production — directed by Lila Neugebauer',
    venue: 'BAM Harvey Theater',
    venueSlug: 'bam-harvey',
    city: 'Brooklyn',
    date: '2026-09-04',
    time: '19:30',
    category: 'performance',
    price: '$45',
    description: 'A new production of Adrienne Kennedy\'s 1964 surrealist drama — a woman, whose father may be Patrice Lumumba, moves through a fractured, multiplying identity on stage. Directed by Lila Neugebauer for BAM\'s Next Wave preview series. Kennedy\'s most performed and least understood work, presented with new design.',
    tags: ['Theater', 'Adrienne Kennedy', 'Surrealism', 'Black Theater']
  },
  {
    id: '023',
    slug: 'demdike-stare-live',
    index: 23,
    title: 'Demdike Stare',
    subtitle: 'Testpressing Tour — Live',
    venue: 'Knockdown Center',
    venueSlug: 'knockdown-center',
    city: 'Queens',
    date: '2026-09-10',
    time: '22:00',
    doorsTime: '21:00',
    category: 'music',
    price: '$25',
    description: 'The Manchester duo — Sean Canty and Miles Whittaker — play a rare live set presenting material from their Testpressing series alongside new unreleased work. Demdike Stare\'s practice moves between industrial, dub techno, and occult electronics; the live format extends all three into something harder to name.',
    tags: ['Industrial', 'Techno', 'Experimental', 'Dub Techno']
  },
  {
    id: '024',
    slug: 'yvonne-rainer-the-man',
    index: 24,
    title: 'The Man Who Envied Women',
    subtitle: 'Dir. Yvonne Rainer, 1985 — 16mm',
    venue: 'Metrograph',
    venueSlug: 'metrograph',
    city: 'New York',
    date: '2026-09-17',
    time: '19:30',
    category: 'film',
    price: '$15',
    description: 'Rainer\'s most theoretically ambitious film — a male academic navigates feminism, desire, and gentrification in 1980s New York. Shot in 16mm. The film speaks in the language of Lacan and downtown politics, but what it says outlasts both. Post-screening discussion with a film scholar.',
    tags: ['Yvonne Rainer', '16mm', 'Feminist Cinema', 'Downtown NY']
  },
  {
    id: 'p001',
    slug: 'andrei-rublev',
    index: 25,
    title: 'Andrei Rublev',
    subtitle: 'Dir. Andrei Tarkovsky, 1966 — 35mm',
    venue: 'Film Forum',
    venueSlug: 'film-forum',
    city: 'New York',
    date: '2026-03-14',
    time: '19:00',
    category: 'film',
    price: '$15',
    description: 'Tarkovsky\'s three-and-a-half hour fresco on art, faith, and survival in fifteenth-century Russia. A restored 35mm print from Mosfilm. Rublev moves through episodes of violence and beauty, silence and fire, arriving at the luminous creation of the Trinity icon. One of the undisputed masterworks of world cinema.',
    tags: ['Tarkovsky', 'Russian Cinema', '35mm', 'Mosfilm'],
    isPast: true
  },
  {
    id: 'p002',
    slug: 'special-interest',
    index: 26,
    title: 'Special Interest',
    subtitle: 'Disrespect Tour — with Automatic',
    venue: 'Elsewhere',
    venueSlug: 'elsewhere',
    city: 'Brooklyn',
    date: '2026-02-21',
    time: '20:00',
    doorsTime: '19:00',
    category: 'music',
    price: '$20',
    description: 'New Orleans synth-punk act Special Interest bring their confrontational live show to Elsewhere for a single night. Guitar, drum machine, bass, and Alli Logout\'s raw vocal against a wall of distortion. Support from LA\'s Automatic. One of the most urgent bands in contemporary punk.',
    tags: ['Post-Punk', 'Synth', 'New Orleans'],
    isPast: true
  },
  {
    id: 'p003',
    slug: 'nan-goldin-ballad',
    index: 27,
    title: 'The Ballad of Sexual Dependency',
    subtitle: 'Nan Goldin — Slideshow, live performance',
    venue: 'MoMA PS1',
    venueSlug: 'ps1',
    city: 'Queens',
    date: '2026-01-17',
    time: '19:30',
    category: 'exhibition',
    price: '$20',
    description: 'Nan Goldin performs her landmark slideshow live — 700 photographs from 1979–1986 projected to the original soundtrack of pop, gospel, and opera that Goldin assembled herself. A document of survival among the downtown demimonde: friends, lovers, drag queens, junkies, and chosen family.',
    tags: ['Photography', 'Downtown NY', 'Slideshow', 'LGBTQ+'],
    isPast: true
  },
  {
    id: 'p004',
    slug: 'cunningham-night',
    index: 28,
    title: 'Night of 100 Solos',
    subtitle: 'Merce Cunningham Dance Foundation — Centennial',
    venue: 'BAM Harvey Theater',
    venueSlug: 'bam-harvey',
    city: 'Brooklyn',
    date: '2025-11-14',
    time: '19:30',
    category: 'performance',
    price: '$45',
    description: 'One hundred dancers from companies around the world perform solos drawn from Cunningham\'s nearly fifty-year choreographic archive simultaneously on a single stage — each solo an autonomous event. The centennial tribute to an artist who redefined what the body could do and what dance could be.',
    tags: ['Cunningham', 'Contemporary Dance', 'Centennial', 'BAM'],
    isPast: true
  },
  {
    id: 'p005',
    slug: 'harun-farocki',
    index: 29,
    title: 'Harun Farocki: Working at the Edges',
    subtitle: 'A retrospective programme',
    venue: 'Anthology Film Archives',
    venueSlug: 'anthology',
    city: 'New York',
    date: '2025-09-19',
    time: '20:00',
    category: 'film',
    price: '$15',
    description: 'A curated evening of Farocki\'s essay films — Workers Leaving the Factory, Images of the World and the Inscription of War, and Inextinguishable Fire. Farocki\'s work examines how images are produced, deployed, and weaponized. Post-screening conversation with the programming team.',
    tags: ['Essay Film', 'Media Theory', 'Labor'],
    isPast: true
  },
  {
    id: 'p006',
    slug: 'peter-hujar-speed-of-life',
    index: 30,
    title: 'Peter Hujar: Speed of Life',
    subtitle: 'Survey exhibition',
    venue: 'ICP Museum',
    venueSlug: 'icp',
    city: 'New York',
    date: '2026-03-07',
    time: '11:00',
    category: 'exhibition',
    price: '$16',
    description: 'A comprehensive survey of Peter Hujar\'s black-and-white photography — intimate portraits of the downtown New York demimonde across the 1970s and 80s. Friends, lovers, drag queens, animals, and architecture rendered with an unnerving directness. ICP\'s largest Hujar exhibition to date.',
    tags: ['Photography', 'Downtown NY', 'Black & White'],
    isPast: true
  },
  {
    id: 'p007',
    slug: 'floating-points-live',
    index: 31,
    title: 'Floating Points',
    subtitle: 'Live — with Pharoah Sanders Ensemble',
    venue: 'Brooklyn Steel',
    venueSlug: 'brooklyn-steel',
    city: 'Brooklyn',
    date: '2026-04-11',
    time: '20:00',
    doorsTime: '19:00',
    category: 'music',
    price: '$30',
    description: 'Sam Shepherd brings his live band setup to Brooklyn Steel — selections from Cascade and LesAlpx alongside material from his collaboration with Pharoah Sanders. A precisely assembled electronic show that moves between jazz abstraction, club music, and something harder to name.',
    tags: ['Electronic', 'Jazz', 'Live Band'],
    isPast: true
  },
  {
    id: 'p008',
    slug: 'jia-zhangke-in-conversation',
    index: 32,
    title: 'Jia Zhangke: In Conversation',
    subtitle: 'Hosted by Museum of the Moving Image',
    venue: 'Museum of the Moving Image',
    venueSlug: 'momi',
    city: 'Queens',
    date: '2026-05-09',
    time: '19:00',
    category: 'lecture',
    price: '$20',
    description: 'A rare public conversation with Jia Zhangke, the foremost chronicler of China\'s industrial transformation. The discussion ranges across his career — from Platform and Still Life to Ash Is Purest White — and addresses the question of how cinema survives in conditions of rapid disappearance.',
    tags: ['Film', 'China', 'Essay Cinema'],
    isPast: true
  }
]

export function useEvents() {
  const events = EVENTS

  function getEventBySlug(slug: string): OutsideEvent | undefined {
    return EVENTS.find(e => e.slug === slug)
  }

  function getEventById(id: string): OutsideEvent | undefined {
    return EVENTS.find(e => e.id === id)
  }

  function filterEvents(city?: string, category?: EventCategory | '') {
    return EVENTS.filter(e => {
      if (e.isPast) return false
      if (city && e.city !== city) return false
      if (category && e.category !== category) return false
      return true
    })
  }

  const cities = [...new Set(EVENTS.map(e => e.city))]
  const categories: EventCategory[] = ['film', 'music', 'lecture', 'exhibition', 'performance']

  return { events, getEventBySlug, getEventById, filterEvents, cities, categories }
}
